
package pruebas.graficoJfreechart;

import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Basado en: http://panamahitek.com/graficando-en-java-con-jfreechart/
 * de Panama Hitek
 */


public class Ventana extends javax.swing.JFrame {
    
    //declaro las variables de la clase Ventana
    JFreeChart grafica;
    DefaultCategoryDataset datos = new DefaultCategoryDataset();
   
    public Ventana() {
        initComponents();
        
        //agregado por dario
        datos.addValue(1, "Sucursal 1", "Lunes");
        datos.addValue(2, "Sucursal 1", "Martes");
        datos.addValue(3, "Sucursal 1", "Miércoles");
        datos.addValue(4, "Sucursal 1", "Jueves");
        datos.addValue(5, "Sucursal 1", "Viernes");
        datos.addValue(6, "Sucursal 1", "Sábado");
        datos.addValue(7, "Sucursal 1", "Domingo");
        
        datos.addValue(1, "Sucursal 2", "Lunes");
        datos.addValue(2, "Sucursal 2", "Martes");
        datos.addValue(3, "Sucursal 2", "Miércoles");
        datos.addValue(4, "Sucursal 2", "Jueves");
        datos.addValue(5, "Sucursal 2", "Viernes");
        datos.addValue(6, "Sucursal 2", "Sábado");
        datos.addValue(7, "Sucursal 2", "Domingo");
        
        
        grafica = ChartFactory.createBarChart("Visitas diarias", "Días", "Visitas", datos, PlotOrientation.VERTICAL, true, true, false);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Agregado por dario
        ChartPanel panel = new ChartPanel(grafica);
        JFrame ventanaDelGrafico = new JFrame("JFreeChart");
        ventanaDelGrafico.getContentPane().add(panel);
        ventanaDelGrafico.pack();
        ventanaDelGrafico.setVisible(true);
        ventanaDelGrafico.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
