
package pruebas.graficoArduino2;

import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.NumberTickUnit;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import panamahitek.Arduino.PanamaHitek_Arduino;

/*
 * Basado en: http://panamahitek.com/graficando-en-java-con-jfreechart/
 * de Panama Hitek
 */


public class Ventana extends javax.swing.JFrame {
    
    //declaro las variables para la conexion con Arduino
    PanamaHitek_Arduino arduino=new PanamaHitek_Arduino();
    
    int i=0;
    SerialPortEventListener evento=new SerialPortEventListener() {

        @Override
        public void serialEvent(SerialPortEvent spe) {
            
            if(arduino.isMessageAvailable()==true){ 
                i++;
                serie.add(i, Integer.parseInt(arduino.printMessage()));   
            }
                    
        }
    };
    
    
    //declaro las variables para graficar con freeChart
    final XYSeries serie= new XYSeries("Luminosidad");
    final XYSeriesCollection coleccion= new XYSeriesCollection();
    JFreeChart grafica;
   
   
    public Ventana() {
        initComponents();
        
        //*****************************************************************************************
        try { 
            arduino.arduinoRXTX("COM10", 9600, evento);
        } catch (Exception ex) {
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        serie.add(0, 0);
        coleccion.addSeries(serie);
        grafica = ChartFactory.createXYLineChart("Luminosidad vs. Tiempo", "Tiempo (seg.)", "Luminosidad", coleccion, PlotOrientation.VERTICAL, true, true, false);

        // Configuro la escala de los ejes x e y
        NumberAxis xAxis = new NumberAxis();
        xAxis.setTickUnit(new NumberTickUnit(1));
        xAxis.setFixedAutoRange(20);
        
        NumberAxis yAxis = new NumberAxis();
        yAxis.setTickUnit(new NumberTickUnit(1));

        // Assign it to the chart
        XYPlot plot = (XYPlot) grafica.getPlot();
        plot.setDomainAxis(xAxis);     
        //otra alternativa: http://stackoverflow.com/questions/11306688/jfreechart-x-and-y-axis-scaling
        //----------------------------------------------------------------------------------------------

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Graficar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // **********************************************************************************************
        ChartPanel panel = new ChartPanel(grafica);
        JFrame ventanaDelGrafico = new JFrame("JFreeChart");
        ventanaDelGrafico.getContentPane().add(panel);
        ventanaDelGrafico.pack();
        ventanaDelGrafico.setVisible(true);
        ventanaDelGrafico.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //------------------------------------------------------------------------------------------------
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
